"""Add users table

Revision ID: 695885df57cb
Revises: f84206db0560
Create Date: 2020-06-29 23:54:54.574596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695885df57cb'
down_revision = 'f84206db0560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
